from pyrogram import *
from pyrogram.errors import *

'''
Cmds

/getlink or /getlink [any name]
/invite or /invite [any name]

'''

@Client.on_message(filters.command(["ilink"]))
async def link(bot, message):
     lin = message.text.split()[1]
     link = await bot.create_chat_invite_link(lin, name=message.from_user.first_name)
     await message.reply_text(f"--**Link Generated**-- \n\n**Link Name - {link.name}\nLink -{link.invite_link}\nGenerated by - {message.from_user.mention}\nGenerated Date - {link.date}**")
    
